---
    - name: Update static page
      copy:
        src: static-page.html
        dest: /var/www/html/static.html

    - name: Update dynamic
      template:
        src: dynamic-page.j2
        dest: /var/www/html/dynamic.html
...
