---
- name: Install httpd on all servers
  hosts: server1
  become: true
  tasks:
    - name: Install HTTPD
      yum:
        name: httpd
        state: present

    - name: Start the service
      yum:
        name: httpd
        state: started

    - name: Start the service
      yum:
        name: httpd
        enabled: yes
...
