---
- name: Create a new directory in node1
  hosts: node1
  become: true
  tasks:
    - name: Create a directory
      file:
        path: /home/ec2-user/test_dir1
        state: directory

    - name: Create a directory
      file:
        path: /home/ec2-user/test_dir2
        state: directory



- name: Create a new directory in node2
  hosts: node2
  become: true
  tasks:
    - name: Create a directory
      file:
        path: /home/ec2-user/test_dir1
        state: directory

    - name: Create a directory
      file:
        path: /home/ec2-user/test_dir2
        state: directory



- name: Create a new directory in node3
  hosts: node3
  become: true
  tasks:
    - name: Create a directory
      file:
        path: /home/ec2-user/test_dir1
        state: directory

    - name: Create a directory
      file:
        path: /home/ec2-user/test_dir2
        state: directory



- name: Create a new directory in node4
  hosts: node4
  become: true
  tasks:
    - name: Create a directory
      file:
        path: /home/fedora/test_dir1
        state: directory

    - name: Create a directory
      file:
        path: /home/fedora/test_dir2
        state: directory



- name: Create a new directory in node5
  hosts: node5
  become: true
  tasks:
    - name: Create a directory
      file:
        path: /home/fedora/test_dir1
        state: directory

    - name: Create a directory
      file:
        path: /home/fedora/test_dir2
        state: directory
...
