---
- name: Deploy web app on all servers
  hosts: all
  become: true
  tasks:
    - name: Install git
      yum:
        name: git
        state: present

    - name: Host code
      git:
        repo: https://github.com/CeeyIT-Solutions/ecomm-3.git
        dest: /var/www/html
...
