---
- name: Install httpd on all servers
  hosts: server3
  become: true
  tasks:
    - name: Install Apache2
      apt:
        name: apache2
        state: present

    - name: Start the service
      service:
        name: apache2
        state: started

    - name: Start the service
      service:
        name: apache2
        enabled: yes
...
