---
- name: Deploy web app on all servers
  hosts: server1
  become: true
  tasks:
    - name: Update static page
      copy:
        src: static-page.html
        dest: /var/www/html/static.html
...
