---
- name: Deploy web app on all servers
  hosts: all
  become: true
  vars:
    myusername: Josh
  tasks:
    - name: Update dynamic
      template:
        src: dynamic-page.j2
        dest: /var/www/html/dynamic.html
...
