---
- name: Update all servers
  hosts: all
  become: true

  tasks:
    - name: Create a directory
      file:
        path: /opt/devops
        state: directory
        mode: '0755'

    - name: Create info.txt with content
      copy:
        dest: /opt/devops/info.txt
        content: "Hello from Ansible"
        mode: '0644'
...
