---
    - name: Install Apache2
      apt:
        name: apache2
        state: present
      when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian" 


    - name: Start the service
      service:
        name: apache2
        state: started
      when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian" 

    - name: Start the service
      service:
        name: apache2
        enabled: yes
      when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian" 

    - name: Install httpd
      yum:
        name: httpd
        state: present
      when: ansible_distribution == "Centos" or ansible_distribution == "Amazon" 
    
    - name: Start the service
      service:
        name: httpd
        state: started
      when: ansible_distribution == "Centos" or ansible_distribution == "Amazon" 
    
    - name: Start the service
      service:
        name: httpd
        enabled: yes
      when: ansible_distribution == "Centos" or ansible_distribution == "Amazon" 
...
